# Generated by Django 6.0.1 on 2026-01-28 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('target', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(default='', max_length=30, null=True)),
                ('username', models.CharField(default='', max_length=255, null=True)),
                ('location', models.CharField(default='', null=True)),
                ('chat_id', models.CharField(max_length=255, unique=True)),
                ('balance', models.FloatField(default=0.0)),
                ('referee', models.BigIntegerField(default=0)),
                ('socials', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.JSONField(null=True)),
                ('phone_number', models.CharField(default='', max_length=30, null=True)),
                ('shipping_address', models.CharField(max_length=255, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sharedpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=30, unique=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('shared_by', models.DateTimeField(auto_now_add=True)),
                ('original_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='telegramApp.posts')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='telegramApp.telegramusers', to_field='chat_id')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='telegram',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='telegramApp.telegramusers', to_field='chat_id'),
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=40)),
                ('members', models.TextField(default='[]')),
                ('group_name', models.CharField(max_length=100)),
                ('group_description', models.TextField()),
                ('group_settings', models.TextField(default='[]')),
                ('telegram', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='telegramApp.telegramusers', to_field='chat_id')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.CharField(max_length=100, unique=True)),
                ('chat_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('telegram', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='telegramApp.telegramusers', to_field='chat_id')),
            ],
        ),
    ]
